version: "3.7"

services:
  web:
    container_name: minitwit
    image: itudevops/go-minitwit:latest
    environment:
      - BUGSNAG_API_KEY=$BUGSNAG_API_KEY
      - BUGSNAG_APP_TYPE=web
    ports:
        - "80:80"
    volumes:
      - db:/app/db:rw
    depends_on:
      - grafana
      - prometheus

  api:
    container_name: minitwit-api
    image: itudevops/go-minitwit:api
    environment:
      - BUGSNAG_API_KEY=$BUGSNAG_API_KEY
      - BUGSNAG_APP_TYPE=api
    ports:
        - "8080:8080"
    volumes:
      - db:/app/db:rw
    depends_on:
      - grafana
      - prometheus

  prometheus:
  image: prom/prometheus
  container_name: prometheus
  volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
  ports:
    - "9090:9090"
  networks:
    - main


grafana:
  image: grafana/grafana:4.5.2
  ports:
    - "3000:3000"  
  networks:
    - main
    
volumes:
  db: 