version: "3.7"

networks:
  elk:
  proxy:
  main:
    name: minitwit-network

volumes:
  grafana-data:
  elk_elasticsearch_data:

services:
  minitwit-frontend:
    container_name: minitwit-frontend
    build:
      context: .
      target: web
    env_file:
      - .minitwit-secrets.env
    networks:
      - main
      - proxy

  minitwit-api:
    container_name: minitwit-api
    build:
      context: .
      target: api
    env_file:
      - .minitwit-secrets.env
    networks:
      - main
      - proxy

  minitwit-prometheus:
    image: prom/prometheus
    container_name: minitwit-prometheus
    # ports:
    #   - 9090:9090
    # expose:
    #   - 9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - main
      - proxy

  minitwit-grafana:
    image: grafana/grafana:4.5.2
    container_name: minitwit-grafana
    volumes:
      - grafana-data:/var/lib/grafana
    expose:
      - 3000
    # ports:
    #   - 3000:3000
    networks:
      - main
      - proxy

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.2.0
    user: root
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - elasticsearch
    networks:
      - elk
      - proxy

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: kibana
    environment:
      elasticsearch.hosts: '["http://elasticsearch:9200"]'
    ports:
      - 5601:5601
    # expose:
    #   - 5601
    depends_on:
      - elasticsearch
    networks:
      - elk
      - proxy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    # ports:
    #   - 9200:9200
    # expose:
    #   - 9200
    volumes: 
      - elk_elasticsearch_data:/usr/share/elasticsearch/data
    environment:
        - cluster.name=docker-logs-elk-cluster
        - xpack.security.enabled=false
        - bootstrap.memory_lock=true
        - ES_JAVA_OPTS=-Xms1g -Xmx1g
        - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - elk
      - proxy

  nginx:
    build: "./nginx"
    container_name: nginx-container
    ports:
    - 80:80
    depends_on:
      - minitwit-frontend
      - minitwit-api
    networks: 
      - proxy