version: "3.7"

# NETWORKS
networks:
  elk:
  main:
    name: minitwit-network

# VOLUMES
volumes:
  grafana-data:
  elk_elasticsearch_data:

# SERVICES
services:
  minitwit-frontend:
    #image: itudevops/go-minitwit:32
    container_name: minitwit-frontend
    env_file:
      - .minitwit-secrets.env
    build:
      context: .
      target: web
    # ports:
    #     - 80:80
    networks:
      - main

  minitwit-api:
    #image: itudevops/go-minitwit-api:32
    container_name: minitwit-api
    build:
      context: .
      target: api
    env_file:
      - .minitwit-secrets.env
    # ports:
    #     - 8080:8080
    networks:
      - main

  minitwit-prometheus:
    image: prom/prometheus
    container_name: minitwit-prometheus
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - main

  minitwit-grafana:
    image: grafana/grafana:4.5.2
    volumes:
      - grafana-data:/var/lib/grafana
    # ports:
    #   - 3000:3000
    networks:
      - main

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.2.0
    user: root
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    environment:
      elasticsearch.hosts: '["http://elasticsearch:9200"]'
    # ports:
    #   - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    # ports:
    #   - 9200:9200
    volumes: 
      - elk_elasticsearch_data:/usr/share/elasticsearch/data
    environment:
        - cluster.name=docker-logs-elk-cluster
        - xpack.security.enabled=false
        - bootstrap.memory_lock=true
        - ES_JAVA_OPTS=-Xms1g -Xmx1g
        - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - elk

  nginx:
      container_name: my_nginx
      image: nginx
      ports:
        - 9200:9200
        - 5601:5601
        - 8881:8881
        - 8882:8882
      depends_on: 
        - "minitwit-frontend"
        - "minitwit-api"
        - "kibana"
        - "elasticsearch"
        - "minitwit-grafana"
