version: "3.7"

services:
  web:
    container_name: minitwit-web
    image: itudevops/go-minitwit:TAG
    restart: always
    environment:
      - BUGSNAG_API_KEY=$BUGSNAG_API_KEY
      - BUGSNAG_APP_TYPE=web
      - DB_PASS=$DB_PASS
      - DB_USER=$DB_USER
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
    ports:
        - "80:80"
    links:
      - grafana
      - prometheus

  api:
    container_name: minitwit-api
    image: itudevops/go-minitwit-api:TAG
    restart: always
    environment:
      - BUGSNAG_API_KEY=$BUGSNAG_API_KEY
      - BUGSNAG_APP_TYPE=api
      - DB_PASS=$DB_PASS
      - DB_USER=$DB_USER
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
    ports:
        - "8080:8080"
    links:
      - grafana
      - prometheus
  
  # db:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: 'minitwit'
  #     MYSQL_USER: 'minitwit'
  #     MYSQL_PASSWORD: $DB_PASS
  #     MYSQL_ROOT_PASSWORD: $DB_PASS
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - /mnt/go_minitwit/mysql_data:/var/lib/mysql:rw
  #   depends_on:
  #     - grafana
  #     - prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - grafana
      - minitwit-api
      - minitwit-web
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:4.5.2
    links:
      - prometheus
    ports:
      - "3000:3000"  
