version: "3.7"

networks:
  elk:

volumes:
  grafana-data:
  elk_elasticsearch_data:

services:
  web:
    image: itudevops/go-minitwit:TAG
    container_name: minitwit_web
    deploy:
      replicas: 4
      update_config:
        delay: 10s
        order: start-first
    restart: always
    environment:
      - BUGSNAG_API_KEY=$BUGSNAG_API_KEY
      - BUGSNAG_APP_TYPE=web
      - DB_PASS=$DB_PASS
      - DB_USER=$DB_USER
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
    ports:
        - "80:80"
    links:
      - grafana
      - prometheus

  api:
    image: itudevops/go-minitwit-api:TAG
    container_name: minitwit_api
    deploy:
      replicas: 4
      update_config:
        delay: 10s
        order: start-first
    restart: always
    environment:
      - BUGSNAG_API_KEY=$BUGSNAG_API_KEY
      - BUGSNAG_APP_TYPE=api
      - DB_PASS=$DB_PASS
      - DB_USER=$DB_USER
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
    ports:
        - "8080:8080"
    links:
      - grafana
      - prometheus
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - grafana
      - api
      - web
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:4.5.2
    links:
      - prometheus
    ports:
      - "3000:3000"  

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.2.0
    user: root
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    environment:
      elasticsearch.hosts: '["http://elasticsearch:9200"]'
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    ports:
      - 9200:9200
    volumes: 
      - elk_elasticsearch_data:/usr/share/elasticsearch/data
    environment:
        - cluster.name=docker-logs-elk-cluster
        - xpack.security.enabled=false
        - bootstrap.memory_lock=true
        - ES_JAVA_OPTS=-Xms1g -Xmx1g
        - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - elk



