# Alpine is chosen for its small footprint
FROM golang:1.17.7-alpine3.15

WORKDIR /app
COPY . ./
# Install Go Dependencies
RUN go mod download && go mod verify
# Install C compiler gcc
RUN apk add build-base
# Build Go Binary
RUN go build -o go-minitwit-api api/api.go

RUN chmod +x go-minitwit-api

# Install Bugsnag Panic Monitor
# It report unhandled panics to Bugsnag
RUN go install github.com/bugsnag/panic-monitor@latest

CMD ["panic-monitor ./go-minitwit-api"]