{
 "title": "GoMinitwit2.0",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "CPU Load %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cpu_load_percentage{job=~\"itu-minitwit-api|itu-minitwit-app\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "up{}" }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "gin_request_total{job=~\"itu-minitwit-api|itu-minitwit-app\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "process_cpu_seconds_total{}" }
   ]
  }
 ]
}