name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Deploy version number'
        required: true
        
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      env:
        PSW: "${{ secrets.DOCKER_PASSWORD }}"
        USR: "${{ secrets.DOCKER_USERNAME }}"
        VER: "${{ github.event.inputs.version }}"
      with:
        host: ${{ secrets.MT_SERVER }}
        username: ${{ secrets.MT_USER }}
        key: ${{ secrets.MT_KEY }}
        envs: PSW,USR,VER
        script: |
          source /root/.profile
          echo $VER > /root/deploy-version
          cd /root/go-minitwit
          git stash
          git pull --all
          sed -ir "s/TAG/$VER/" docker-compose.prod.yml
          docker pull itudevops/go-minitwit:$VER
          docker pull itudevops/go-minitwit-api:$VER
          docker stack deploy --compose-file docker-compose.prod.yml minitwit
          docker service scale minitwit_api=4 minitwit_web=4

