name: Deploy

on:
  release:
    types: [published]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      env:
        PSW: "${{ secrets.DOCKER_PASSWORD }}"
        USR: "${{ secrets.DOCKER_USERNAME }}"
      with:
        host: ${{ secrets.MT_SERVER }}
        username: ${{ secrets.MT_USER }}
        key: ${{ secrets.MT_KEY }}
        envs: PSW,USR 
        script: |
          source /root/.profile
          echo $PSW | docker login -u $USR --password-stdin
          cd /root/go-minitwit
          git pull --all
          docker-compose pull
          docker-compose up -d
