name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push App
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gominitwit:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/gominitwit:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/gominitwit:webbuildcache,mode=max
      -
        name: Build and push API
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gominitwit:api
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/gominitwit:apibuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/gominitwit:apibuildcache,mode=max
