name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches: [ develop ]

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          github_token: ${{ secrets.GH_TOKEN }}
          force: true

      - run: git remote -v

      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github,.idea,.bib,src/.DS_Store,pen_report.html,report,Drawio,docs,src/web/.DS_Store, licens, README.md"
     